#
# Run pre-commit hooks. You can run them without installing
#  the hook with
#
# $ pre-commit run --all-files
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-xml
    -   id: detect-private-key
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.1
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/myint/autoflake
  rev: v2.2.1
  hooks:
    - id: autoflake
      args:
        - --in-place
        - --remove-unused-variables
        - --remove-all-unused-imports
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.6
  hooks:
    - id: bandit
      name: bandit
      args: ["-c", ".bandit.yaml"]
      description: 'Bandit is a tool for finding common security issues in Python code'
      entry: bandit
      language: python
      language_version: python3
      types: [python]
- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.3.2
  hooks:
    - id: python-safety-dependencies-check
      files: requirements.txt
      args: ["--short-report"]
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.10.0
  hooks:
  -   id: shellcheck
